# Generated by Django 4.2.23 on 2026-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("available", "Available"), ("unavailable", "Unavailable")],
                default="available",
                max_length=20,
            ),
        ),
    ]
